version: '3.3'
services:

  db:
    image: postgres:14.4-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  django:
    container_name: django
    image: erges699/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    image: frontend
    volumes:
      - frontend:/app/result_build/
      - static_value:/app/result_build/build/static/

  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - django

volumes:
  postgres_data:
  frontend:
  static_value:
  media_value:
