# Generated by Django 4.0.6 on 2022-08-05 13:34

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательное поле. 150 символов или меньше.Только буквы, цифры и @/./+/-/_', max_length=150, unique=True, validators=[users.validators.username_validator], verbose_name='Имя пользователя'),
        ),
    ]
